version: '2'
services:
  frontend-ms:
    build: .
    environment:
      BACK_PORT: '5000'
      BACK_URL: '10.0.0.3'
      HOST_PORT: '5010'
      HOST_URL: '0.0.0.0'
      FILE_ACCESS: '10.0.0.4'
      UPLOAD: '10.0.0.4'
    ports:
      - '5010:5010'
